Store/Components/ShoppingCartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Store.DataService;
using Store.Models.Entities;
using Store.Models.ViewModels;

namespace Store.Components
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke() 
        {
            var cart = new ShoppingCart();
            if (HttpContext.Session.Keys.Contains("cart"))
            {
                cart = HttpContext.Session.GetObj<ShoppingCart>("cart");

            }
            return View("ShoppingCart", cart);
        }
    }
}

Store/Components/UserViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Store.Components
{
    public class UserViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var user = User.Identity.Name;
            return View("User", user);
        }
    }
}

Store/Controllers/CatalogController.cs
using Microsoft.AspNetCore.Mvc;
using Store.DataService;
using Store.Models.ViewModels;

namespace Store.Controllers
{
    public class CatalogController : Controller
    {
        private DataManager _dataManager;

        public CatalogController(DataManager dataManager)
        {
            _dataManager = dataManager;
        }

        public IActionResult Index(int page = 1)
        {
            int pageSize = 6;

            var products = _dataManager.ProductService.GetProducts();
            var count = products.Count();
            var items = products.Skip((page - 1) * pageSize).Take(pageSize).ToList();
            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            IndexViewModel indexViewModel = new IndexViewModel
            {
                PageViewModel = pageViewModel,
                Products = items,
            };
            return View(indexViewModel);
        }
    }
}

Store/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Store</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Store.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
          <div class="container-fluid">
            <div class="collapse navbar-collapse">
              <ul class="navbar-nav me-auto my-1">
                <li class="nav-item">
                  <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                </li>
                <li class="nav-item">
                  <a class="navbar-brand" asp-area="" asp-controller="Catalog" asp-action="Index">Каталог товаров</a>
                </li>
            </div>
                <ul class="nav nav-pills me-auto mb-lg-0">
                      <li>
                          @await Component.InvokeAsync("ShoppingCart")
                      </li>
                      <li class="nav-item">
                          @if(!User.Identity.IsAuthenticated)
                            {
                                <a class="nav-link active" asp-area="" asp-controller="Account" asp-action="Login" role="button">Вход в личный кабинет</a>
                            }
                      </li>
                      <li class="nav-item">
                          @if (User.Identity.IsAuthenticated)
                            {
                                @await Component.InvokeAsync("User")
                            }
                      </li>
                </ul>
            </div>
          </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Store - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>